version : "2.1"
services:
    postgres-data:
        image: 
            busybox:1.26.2
    postgres:
        build:
            context: ./Postgres
            dockerfile: Dockerfile
        ports:
            - "5432:5432"
        volumes_from:
            - postgres-data
        depends_on:
            - postgres-data
        env_file:
            - ./postgres-secrets.properties
    keycloak-postgres:
        image:
            jboss/keycloak-postgres:2.5.4.Final
        ports:
            - "8081:8080"
        volumes_from:
            - postgres
        depends_on:
            - postgres
        env_file:
            - ./keycloak-postgres-secrets.properties
    sso-wildfly-dev:
        build:
            context: ./Wildfly
            dockerfile: Dockerfile
            args:
                - DB_DRIVER_URL=https://jdbc.postgresql.org/download/postgresql-42.0.0.jar
                - PREPARE_CLI=install-offline-dev.cli
                - START_SCRIPT=start-dev.sh
        image: sso-wildfly
        ports:
            - "8080:8080"
            - "8787:8787"
            - "9990:9990"
        depends_on:
            - postgres
            - keycloak-postgres
        links:
            - postgres
        env_file:
            - ./wildfly-secrets.properties
