version : "2.1"
services:
    postgres-data:
        container_name: 
            postgres-data
        image: 
            busybox:1.26.2
    postgres:
        container_name: 
            postgres
        build:
            context: ./Postgres
            dockerfile: Dockerfile
        ports:
            - "5432:5432"
        volumes_from:
            - postgres-data
        volumes:
            - c:/Users/Thomas/docker-backup/jee-7-sso:/tmp/backups
        depends_on:
            - postgres-data
        env_file:
            - ./postgres-secrets.properties
        networks:
            mynet:
                 ipv4_address: 172.25.0.2
    keycloak-postgres:
        container_name: 
            keycloak-postgres
        image:
            jboss/keycloak-postgres:2.5.4.Final
        ports:
            - "8080:8080"
        volumes_from:
            - postgres
        depends_on:
            - postgres
        environment:
            - KEYCLOAK_LOGLEVEL=TRACE
        env_file:
            - ./keycloak-postgres-secrets.properties
        networks:
            mynet:
                 ipv4_address: 172.25.0.3
    sso-wildfly-dev:
        container_name: 
            sso-wildfly-dev
        build:
            context: ./Wildfly
            dockerfile: Dockerfile
            args:
                - DB_DRIVER_URL=https://jdbc.postgresql.org/download/postgresql-42.0.0.jar
                - PREPARE_CLI=install-offline-dev.cli
                - START_SCRIPT=start-dev.sh
        image: sso-wildfly
        ports:
            - "8081:8080"
            - "8787:8787"
            - "9990:9990"
        depends_on:
            - postgres
            - keycloak-postgres
        links:
            - postgres
        env_file:
            - ./wildfly-secrets.properties
        extra_hosts:
            surface: 10.29.18.92
        networks:
            mynet:
                 ipv4_address: 172.25.0.4
networks:
  mynet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24