version : "2.1"
services:
    postgres-data:
        image: 
            busybox:latest
    postgres:
        build:
            context: ./Postgres
            dockerfile: Dockerfile
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_ROOT_PASSWORD=password
            - POSTGRES_DB=postgres
            - DB_USERS=keycloak=keycloak,wildfly=wildfly
            - DB_NAMES=keycloakDB=keycloak,wildflyDB=wildfly
        volumes_from:
            - postgres-data
        depends_on:
            - postgres-data
    keycloak-postgres:
        image:
            jboss/keycloak-postgres:2.5.4.Final
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - POSTGRES_DATABASE=keycloakdb
            - POSTGRES_USER=keycloak
            - POSTGRES_PASSWORD=keycloak
            - POSTGRES_PORT_5432_TCP_ADDR=postgres
            - POSTGRES_PORT_5432_TCP_PORT=5432
        ports:
            - "8081:8080"
        volumes_from:
            - postgres
        depends_on:
            - postgres
    sso-wildfly-dev:
        build:
            context: ./Wildfly
            dockerfile: Dockerfile
            args:
                - DB_DRIVER_URL=https://jdbc.postgresql.org/download/postgresql-42.0.0.jar
                - PREPARE_CLI=install-offline-dev.cli
                - START_SCRIPT=start-dev.sh
        image: sso-wildfly
        ports:
            - "8080:8080"
            - "8787:8787"
            - "9990:9990"
        environment:
            - ADMIN_USER=admin
            - ADMIN_PASSWORD=password
            - POSTGRES_DB=wildflydb
            - POSTGRES_USER=wildfly
            - POSTGRES_PASSWORD=wildfly
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - jsf.ProjectStage=Development
        depends_on:
            - postgres
            - keycloak-postgres
        links:
            - postgres
